### ISSUE TITLE
Some providers have reversed AssetPair

### ISSUE THREAD

**Issue by nullablebool** [hitchhiker/prime#6]
Bittrex for example uses QUOTE-ASSET as its format. Given the current architecture AssetPairs are assumed to always have ASSET precede but this is not enforced.

I may be missing something entirely, however, from what I can see; if this is the case with a Provider then we must make sure we reverse the AssetPair before surfacing it.

A few proposals:

1) Expose a property to IDescribeAssets; e.g. enum AssetPairFormat.QuoteAsset or bool IsAssetPairReversed.

2) Add a similar to IAssetCodeConverter - less intrusive.

3) Implement an IAssetPairConverter.

I'm happy to implement the change if you agree. Otherwise let me know if I'm missing something or if I should just continue to reverse the pair as needed.

**Comment by Alyasko** [comment]
As I understand, saying QUOTE-ASSET format you mean that first asset code is "Quote asset" and second is "Base asset". 

Our idea is to normalize each exchange's API so that we have unified interfaces for working with them in Prime. The standard format of asset pairs approved in Prime is "BASE-QUOTE" (BTC-USD, ETH-USD) where the price for base asset is expressed in quote asset (for BTC-USD the price will be something like $10,000). 

However, some exchanges have different format (like Bittrex), where when you query price for BTC-USD market (normal format) you get the value 1/10,000 = 0.0001 BTC which is actually the price for USD-BTC market (we call these exchanges "reversed"). So whenever we find out that exchange has non-normalized asset pairs format (or call it "reversed" format: "QUOTE-BASE") we do reversal of prices. You can see that in `BittrexProvider.GetPriceAsync`, we use `context.Pair.Reversed` and `MarketPrices(price.Reversed)`.

AssetPair class itself does not care which format is globally used (BASE-QUOTE or QUOTE-BASE), the asset pairs format and reversals are handled in other classes (MarketPrice, OrderBookRecord and other).

If you have any other questions/issues, we will be glad to answer/solve them.

**Comment by nullablebool** [comment]
Thanks for the prompt reply. This is understood and I see the current implementation. I will continue to just use .Reversed when appropriate.

I should have noted that I just wanted to bring it up for discussion as it is usually at a provider level, I thought it may be useful enforcing it so it conforms to the Prime's "BASE-QUOTE". I understand it is not a bug, or issue.

**Comment by hitchhiker** [comment]
Hey @nullablebool, additionally we try to preserve the 'raw' unaltered data as much as possible during the normalisation efforts. When we reverse prices we pass back the original object (in most cases, eventually in all). 
Also we can't place a single flag on an interface, as some (not sure if found yet) exchanges could decide to work one way for 'endpoint a' but anther for 'endpoint b'. Hence only the returned data object can reliably describe what happened on any given 'endpoint'.
Hope this helps..
